### ISSUE TITLE
Eclair does not work with Bitcoin Core 0.19.0.1

### ISSUE THREAD

**Issue by NicolasDorier** [btcpayserver/BTCPayServer.Lightning#26]
Hey @araspitzu  @Kukks , it seems eclair tests do not work with 0.19.0.1.
We need to update Bitcoin Core for BTCPayServer, so this will break Eclair if not fixed.

**Comment by NicolasDorier** [comment]
it seems it fails creating a channel to each other as state stays "WAIT_FOR_FUNDING_CONFIRMED"

**Comment by NicolasDorier** [comment]
No errors nowhere, just channels stay in `WAIT_FOR_FUNDING_CONFIRMED`. The internal status show that the nodes are actually keeping up with the blockchain.

I don't have time to look around, so for now I disable Eclair in the tests.
It may or may not break on BTCPayServer, those tests need to be fixed if you don't want us to break things unexpectedly later.

**Comment by araspitzu** [comment]
Sorry for the late reply, i was on holiday :). Eclair *should* work with bitcoin 0.19 but i haven't checked the build/test, i'll have a look.

**Comment by araspitzu** [comment]
The reason for eclair's channels to be stuck at state `WAIT_FOR_FUNDING_CONFIRMED` is that eclair is unable to lookup the transactions via `getrawtransaction`, this is caused by the missing the txindex in bitcoind. Commit https://github.com/araspitzu/BTCPayServer.Lightning/commit/d4f7e16c9f05d3cf491119693f1c4eb77b446995 enables the index and the channels get to `NORMAL`, i also see several payment being successfully made between `test_eclair_1` and `test_eclair_dest_1`. I wonder how it was working without the index.
